#debug: true
spring:
  application:
    name: 02-grpc-client

  grpc:
    client:
      channels:
        local:
          health:
            enabled: true
#            service-name: "Simple" #    就是不行。。。。
          address: "static://localhost:9090"
          negotiation-type: plaintext



server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"
